### ISSUE TITLE
11. Building a CSS menu

### ISSUE THREAD

**Issue by ReneKrewinkel** [BennoBalter/educom-css#12]
<ul>
<li>Module: <a href="https://e-learning.educom.nu/essentials/CSS/css-menu">https://e-learning.educom.nu/essentials/CSS/css-menu</a></li>
<li>Doorloop de module</li>
<li>Maak de opdracht</li>
<li>Commit en push de repository naar github</li>
</ul>

**Comment by BennoBalter** [comment]
Welk uiterlijk effect heeft de selector met class "menu"  nou eigenlijk? Alleen op de inhoud van de menulijst?
Klopt het dat deze CSS selector geen effect heeft/niet zichtbaar is?
.menu-trigger:hover {
    background-color: #FFF000;
}
