### ISSUE TITLE
13. Oefening

### ISSUE THREAD

**Issue by ReneKrewinkel** [BennoBalter/educom-css#14]
<p>Maak de oefening op <a href="https://e-learning.educom.nu/essentials/CSS/exercise">https://e-learning.educom.nu/essentials/CSS/exercise</a></p>
<p>En commit je werk naar github</p>

**Comment by BennoBalter** [comment]
Margin wordt dus wel toegepast op navigation maar niet op footer?
html, body{
    margin: 0 !important;
